### ISSUE TITLE
create new habit for tracking

### ISSUE THREAD

**Issue by chekkan** [pillaru/habit-tracker#2]
- [x] Save to SQL Lite database
- [x] Raw SQL and DBTransactions - or use dapper???
   - No dependencies with raw sql ?
   - Dapper takes care of conversion to c# types.
- [x] Use Fluent Migrator library for creating database
   - Check dependencies...
